/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.KeyEvent;
import java.util.HashMap;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Rahmad Al Habib Khasari <rahmadalhabib89@gmail.com>
 */
public class kendaraan extends javax.swing.JFrame {

    public String roleUser = "";
    public String userName = "";
    private Connection conn = new koneksi().connect();
    private DefaultTableModel tabmode;

    /**
     * Creates new form kendaraan
     */
    public kendaraan() {
        initComponents();
        kosong();
        aktif();
        datatable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        noplat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tahun = new javax.swing.JTextField();
        tarif = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        kButton1 = new keeptoo.KButton();
        kButton2 = new keeptoo.KButton();
        kButton3 = new keeptoo.KButton();
        kButton4 = new keeptoo.KButton();
        kButton6 = new keeptoo.KButton();
        txtcari = new javax.swing.JTextField();
        kButton5 = new keeptoo.KButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblplgn = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        namaKend = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        merk = new javax.swing.JComboBox<>();
        tipe = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        rya = new javax.swing.JRadioButton();
        rtidak = new javax.swing.JRadioButton();
        jLabel9 = new javax.swing.JLabel();
        pemilik = new javax.swing.JComboBox<>();
        print = new keeptoo.KButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnTransaksi = new javax.swing.JMenu();
        mnKendaraan = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        mnMerek = new javax.swing.JMenuItem();
        mnTipe = new javax.swing.JMenuItem();
        mnSopir = new javax.swing.JMenu();
        mnPelanggan = new javax.swing.JMenu();
        mnPemilik = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        jMenu8 = new javax.swing.JMenu();
        jMenu9 = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Data Kendaraan");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        kGradientPanel1.setkEndColor(new java.awt.Color(34, 167, 240));
        kGradientPanel1.setkStartColor(new java.awt.Color(83, 51, 237));

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(233, 226, 226));
        jLabel1.setText("Data Kendaraan");

        jLabel2.setForeground(new java.awt.Color(41, 26, 26));
        jLabel2.setText("No Plat");

        noplat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                noplatActionPerformed(evt);
            }
        });

        jLabel3.setText("Tahun");

        tahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tahunActionPerformed(evt);
            }
        });

        tarif.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tarifActionPerformed(evt);
            }
        });

        jLabel4.setText("Tarif");

        jLabel5.setText("Status Rental");

        kButton1.setText("Simpan");
        kButton1.setkEndColor(new java.awt.Color(46, 204, 113));

        kButton1.setkForeGround(new java.awt.Color(0, 0, 0));

        kButton1.setkHoverColor(new java.awt.Color(0, 0, 0));

        kButton1.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kButton1.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        kButton1.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        kButton1.setkSelectedColor(new java.awt.Color(46, 204, 113));

        kButton1.setkStartColor(new java.awt.Color(0, 230, 64));
        kButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton1ActionPerformed(evt);
            }
        });

        kButton2.setText("Ubah");
        kButton2.setkEndColor(new java.awt.Color(46, 204, 113));

        kButton2.setkForeGround(new java.awt.Color(0, 0, 0));

        kButton2.setkHoverColor(new java.awt.Color(0, 0, 0));

        kButton2.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kButton2.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        kButton2.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        kButton2.setkSelectedColor(new java.awt.Color(46, 204, 113));

        kButton2.setkStartColor(new java.awt.Color(0, 230, 64));
        kButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton2ActionPerformed(evt);
            }
        });

        kButton3.setText("Hapus");
        kButton3.setkEndColor(new java.awt.Color(46, 204, 113));

        kButton3.setkForeGround(new java.awt.Color(0, 0, 0));

        kButton3.setkHoverColor(new java.awt.Color(0, 0, 0));

        kButton3.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kButton3.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        kButton3.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        kButton3.setkSelectedColor(new java.awt.Color(46, 204, 113));

        kButton3.setkStartColor(new java.awt.Color(0, 230, 64));
        kButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton3ActionPerformed(evt);
            }
        });

        kButton4.setText("Batal");
        kButton4.setkEndColor(new java.awt.Color(46, 204, 113));

        kButton4.setkForeGround(new java.awt.Color(0, 0, 0));

        kButton4.setkHoverColor(new java.awt.Color(0, 0, 0));

        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kButton4.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        kButton4.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        kButton4.setkSelectedColor(new java.awt.Color(46, 204, 113));

        kButton4.setkStartColor(new java.awt.Color(0, 230, 64));
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton6.setText("Keluar");
        kButton6.setkEndColor(new java.awt.Color(46, 204, 113));

        kButton6.setkForeGround(new java.awt.Color(0, 0, 0));

        kButton6.setkHoverColor(new java.awt.Color(0, 0, 0));

        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kButton6.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        kButton6.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        kButton6.setkSelectedColor(new java.awt.Color(46, 204, 113));

        kButton6.setkStartColor(new java.awt.Color(0, 230, 64));
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        txtcari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtcariKeyPressed(evt);
            }
        });

        kButton5.setText("Cari");
        kButton5.setkEndColor(new java.awt.Color(46, 204, 113));

        kButton5.setkForeGround(new java.awt.Color(0, 0, 0));

        kButton5.setkHoverColor(new java.awt.Color(0, 0, 0));

        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        kButton5.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        kButton5.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        kButton5.setkSelectedColor(new java.awt.Color(46, 204, 113));

        kButton5.setkStartColor(new java.awt.Color(0, 230, 64));
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        tblplgn.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblplgn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblplgnMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblplgn);

        jLabel6.setText("Nama");

        jLabel7.setText("Merk");

        merk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        tipe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel8.setText("Tipe");

        buttonGroup1.add(rya);
        rya.setText("Ya");

        buttonGroup1.add(rtidak);
        rtidak.setText("Tidak");

        jLabel9.setText("Pemilik");

        pemilik.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        print.setText("Print");
        print.setkEndColor(new java.awt.Color(46, 204, 113));

        print.setkForeGround(new java.awt.Color(0, 0, 0));

        print.setkHoverColor(new java.awt.Color(0, 0, 0));

        print.setkHoverForeGround(new java.awt.Color(255, 255, 255));

        print.setkHoverStartColor(new java.awt.Color(30, 130, 76));

        print.setkIndicatorColor(new java.awt.Color(0, 0, 0));

        print.setkSelectedColor(new java.awt.Color(46, 204, 113));

        print.setkStartColor(new java.awt.Color(0, 230, 64));
        print.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(69, 69, 69)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(noplat)
                            .addComponent(namaKend)
                            .addComponent(merk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(32, 32, 32)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tarif)
                            .addComponent(tahun)
                            .addComponent(tipe, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pemilik, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(rya)
                                .addGap(18, 18, 18)
                                .addComponent(rtidak)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(162, 162, 162))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(129, Short.MAX_VALUE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(102, 102, 102)
                        .addComponent(txtcari, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(232, 232, 232))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 690, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(32, 32, 32))))))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(noplat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(namaKend, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(merk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tipe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(15, 15, 15)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tahun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tarif, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rya)
                    .addComponent(rtidak)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(pemilik, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, 27, Short.MAX_VALUE)
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtcari)
                    .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addComponent(print, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jMenuBar1.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                jMenuBar1ComponentAdded(evt);
            }
        });
        jMenuBar1.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jMenuBar1ComponentShown(evt);
            }
        });

        mnTransaksi.setText("Transaksi");
        mnTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnTransaksiMousePressed(evt);
            }
        });
        mnTransaksi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTransaksiActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnTransaksi);

        mnKendaraan.setText("Kendaraan");

        jMenuItem1.setText("Kendaraan");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnKendaraan.add(jMenuItem1);

        mnMerek.setText("Merk");
        mnMerek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMerekActionPerformed(evt);
            }
        });
        mnKendaraan.add(mnMerek);

        mnTipe.setText("Tipe");
        mnTipe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnTipeActionPerformed(evt);
            }
        });
        mnKendaraan.add(mnTipe);

        jMenuBar1.add(mnKendaraan);

        mnSopir.setText("Sopir");
        mnSopir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnSopirMousePressed(evt);
            }
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnSopirMouseClicked(evt);
            }
        });
        mnSopir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnSopirActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnSopir);

        mnPelanggan.setText("Pelanggan");
        mnPelanggan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnPelangganMousePressed(evt);
            }
        });
        mnPelanggan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPelangganActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnPelanggan);

        mnPemilik.setText("Pemilik");
        mnPemilik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mnPemilikMousePressed(evt);
            }
        });
        mnPemilik.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnPemilikActionPerformed(evt);
            }
        });
        jMenuBar1.add(mnPemilik);

        jMenu7.setText("Karyawan");
        jMenu7.addMenuKeyListener(new javax.swing.event.MenuKeyListener() {
            public void menuKeyPressed(javax.swing.event.MenuKeyEvent evt) {
                jMenu7MenuKeyPressed(evt);
            }
            public void menuKeyReleased(javax.swing.event.MenuKeyEvent evt) {
            }
            public void menuKeyTyped(javax.swing.event.MenuKeyEvent evt) {
            }
        });
        jMenu7.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu7MenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu7MousePressed(evt);
            }
        });
        jMenu7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu7ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu7);

        jMenu8.setText("Users");
        jMenu8.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu8MenuSelected(evt);
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
        });
        jMenu8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu8MousePressed(evt);
            }
        });
        jMenu8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu8ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu8);

        jMenu9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jMenu9MousePressed(evt);
            }
        });
        jMenu9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu9ActionPerformed(evt);
            }
        });

        jMenuItem4.setText("Logout");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu9.add(jMenuItem4);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void noplatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_noplatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_noplatActionPerformed

    private void tahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tahunActionPerformed

    private void tarifActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tarifActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tarifActionPerformed

    private void kButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton1ActionPerformed
        String sql = "insert into kendaraan values (?,?,?,?,?,?,?,?)";
        String statusRe = null;
        if (rya.isSelected()) {
            statusRe = "Ya";
        } else if (rtidak.isSelected()) {
            statusRe = "Tidak";
        }
        try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, noplat.getText());
            stat.setString(2, namaKend.getText());
            stat.setString(3, tahun.getText());
            stat.setString(4, tarif.getText());
            stat.setString(5, statusRe);
            stat.setString(6, merk.getSelectedItem().toString());
            stat.setString(7, tipe.getSelectedItem().toString());
            stat.setString(8, pemilik.getSelectedItem().toString());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
            noplat.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal disimpan" + e);
        }
        datatable();
    }//GEN-LAST:event_kButton1ActionPerformed

    private void kButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton2ActionPerformed
        noplat.setEditable(true);
        String statusRe = null;
        if (rya.isSelected()) {
            statusRe = "Ya";
        } else if (rtidak.isSelected()) {
            statusRe = "Tidak";
        }
        try {
            String sql = "update kendaraan set namaKendaraan=?, tahun=?,tarif=?,statusRental=?,merekKendaraan=?,tipeKendaraan=?,namaPemilik=? where noPlat ='" + noplat.getText() + "'  ";

            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, namaKend.getText());
            stat.setString(2, tahun.getText());
            stat.setString(3, tarif.getText());
            stat.setString(4, statusRe);
            stat.setString(5, merk.getSelectedItem().toString());
            stat.setString(6, tipe.getSelectedItem().toString());
            stat.setString(7, pemilik.getSelectedItem().toString());
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
            noplat.requestFocus();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "data gagal diubah" + e);
        }
        datatable();
    }//GEN-LAST:event_kButton2ActionPerformed

    private void kButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton3ActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog ", JOptionPane.YES_NO_OPTION);
        if (ok == 0) {
            String sql = "delete from kendaraan where noPlat ='" + noplat.getText() + "'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
                noplat.setEditable(true);
                noplat.requestFocus();
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(null, "data gagal dihapus" + e);
            }
            datatable();
        }
    }//GEN-LAST:event_kButton3ActionPerformed

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        kosong();
        datatable();
        noplat.setEditable(true);
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        dispose();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void txtcariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcariKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            datatable();
        }
    }//GEN-LAST:event_txtcariKeyPressed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        datatable();
    }//GEN-LAST:event_kButton5ActionPerformed

    private void tblplgnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblplgnMouseClicked
        Object[] Baris = {"No Plat", "Nama Kendaraan", "Tahun", "Tarif", "Status", "Merek", "Tipe", "Pemilik"};
        int bar = tblplgn.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        noplat.setEditable(false);
        noplat.setText(a);
        namaKend.setText(b);
        tahun.setText(c);
        tarif.setText(d);
        if ("Ya".equals(e)) {
            rya.setSelected(true);
        } else {
            rtidak.setSelected(true);
        }
        merk.setSelectedItem(f);
        tipe.setSelectedItem(g);
        pemilik.setSelectedItem(h);
    }//GEN-LAST:event_tblplgnMouseClicked

    private void mnTransaksiMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnTransaksiMousePressed
        dispose();
        transaksi transak = new transaksi();
        transak.componentDidUpdate(roleUser, userName);
        transak.setVisible(true);
    }//GEN-LAST:event_mnTransaksiMousePressed

    private void mnTransaksiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTransaksiActionPerformed

    }//GEN-LAST:event_mnTransaksiActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        dispose();
        kendaraan kendar = new kendaraan();
        kendar.componentDidUpdate(roleUser, userName);
        kendar.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void mnMerekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMerekActionPerformed
        dispose();
        merekKendaraan merekKendar = new merekKendaraan();
        merekKendar.componentDidUpdate(roleUser, userName);
        merekKendar.setVisible(true);
    }//GEN-LAST:event_mnMerekActionPerformed

    private void mnTipeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnTipeActionPerformed
        dispose();
        tipeKendaraan tipeKendar = new tipeKendaraan();
        tipeKendar.componentDidUpdate(roleUser, userName);
        tipeKendar.setVisible(true);
    }//GEN-LAST:event_mnTipeActionPerformed

    private void mnSopirMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSopirMousePressed
        dispose();
        sopir sop = new sopir();
        sop.componentDidUpdate(roleUser, userName);
        sop.setVisible(true);
    }//GEN-LAST:event_mnSopirMousePressed

    private void mnSopirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnSopirMouseClicked

    }//GEN-LAST:event_mnSopirMouseClicked

    private void mnSopirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnSopirActionPerformed

    }//GEN-LAST:event_mnSopirActionPerformed

    private void mnPelangganMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPelangganMousePressed
        dispose();
        pelanggan pelangg = new pelanggan();
        pelangg.componentDidUpdate(roleUser, userName);
        pelangg.setVisible(true);
    }//GEN-LAST:event_mnPelangganMousePressed

    private void mnPelangganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPelangganActionPerformed

    }//GEN-LAST:event_mnPelangganActionPerformed

    private void mnPemilikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnPemilikMousePressed
        dispose();
        pemilik milik = new pemilik();
        milik.componentDidUpdate(roleUser, userName);
        milik.setVisible(true);
    }//GEN-LAST:event_mnPemilikMousePressed

    private void mnPemilikActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnPemilikActionPerformed

    }//GEN-LAST:event_mnPemilikActionPerformed

    private void jMenu7MenuKeyPressed(javax.swing.event.MenuKeyEvent evt) {//GEN-FIRST:event_jMenu7MenuKeyPressed

    }//GEN-LAST:event_jMenu7MenuKeyPressed

    private void jMenu7MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu7MenuSelected
        dispose();
        karyawan karyaw = new karyawan();
        karyaw.componentDidUpdate(roleUser, userName);
        karyaw.setVisible(true);
    }//GEN-LAST:event_jMenu7MenuSelected

    private void jMenu7MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu7MousePressed

    }//GEN-LAST:event_jMenu7MousePressed

    private void jMenu7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu7ActionPerformed

    }//GEN-LAST:event_jMenu7ActionPerformed

    private void jMenu8MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu8MenuSelected
        dispose();
        users use = new users();
        use.componentDidUpdate(roleUser, userName);
        use.setVisible(true);
    }//GEN-LAST:event_jMenu8MenuSelected

    private void jMenu8MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu8MousePressed

    }//GEN-LAST:event_jMenu8MousePressed

    private void jMenu8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu8ActionPerformed

    }//GEN-LAST:event_jMenu8ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        dispose();
        new fLogin().setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenu9MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu9MousePressed
        //        dispose();
        //        new fLogin().setVisible(true);
    }//GEN-LAST:event_jMenu9MousePressed

    private void jMenu9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu9ActionPerformed

    }//GEN-LAST:event_jMenu9ActionPerformed

    private void jMenuBar1ComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentAdded

    }//GEN-LAST:event_jMenuBar1ComponentAdded

    private void jMenuBar1ComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jMenuBar1ComponentShown

    }//GEN-LAST:event_jMenuBar1ComponentShown

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        if (this.roleUser.equals("Karyawan")) {
            jMenu7.setEnabled(false);
            jMenu8.setEnabled(false);
        }
    }//GEN-LAST:event_formWindowOpened

    private void printActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printActionPerformed
        cetak();
    }//GEN-LAST:event_printActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(kendaraan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new kendaraan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KButton kButton1;
    private keeptoo.KButton kButton2;
    private keeptoo.KButton kButton3;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton5;
    private keeptoo.KButton kButton6;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JComboBox<String> merk;
    private javax.swing.JMenu mnKendaraan;
    private javax.swing.JMenuItem mnMerek;
    private javax.swing.JMenu mnPelanggan;
    private javax.swing.JMenu mnPemilik;
    private javax.swing.JMenu mnSopir;
    private javax.swing.JMenuItem mnTipe;
    private javax.swing.JMenu mnTransaksi;
    private javax.swing.JTextField namaKend;
    private javax.swing.JTextField noplat;
    private javax.swing.JComboBox<String> pemilik;
    private keeptoo.KButton print;
    private javax.swing.JRadioButton rtidak;
    private javax.swing.JRadioButton rya;
    private javax.swing.JTextField tahun;
    private javax.swing.JTextField tarif;
    private javax.swing.JTable tblplgn;
    private javax.swing.JComboBox<String> tipe;
    private javax.swing.JTextField txtcari;
    // End of variables declaration//GEN-END:variables

    private void kosong() {
        namaKend.setText("");
        noplat.setText("");
        tahun.setText("");
        tarif.setText("");
        buttonGroup1.clearSelection();
        txtcari.setText("");
    }

    private void aktif() {
        noplat.requestFocus();
    }

    private void datatable() {
        Object[] Baris = {"No Plat", "Nama Kendaraan", "Tahun", "Tarif", "Status", "Merek", "Tipe", "Pemilik"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();
        try {
            String sql = "SELECT * FROM kendaraan where noPlat like '%" + cariitem + "%' or tahun like '%" + cariitem + "%' or namaKendaraan like '%" + cariitem + "%' or namaPemilik like '%" + cariitem + "%' order by noPlat asc ";
            String sql2 = "SELECT * FROM merekKendaraan";
            String sql3 = "SELECT * FROM tipeKendaraan";
            String sql4 = "SELECT * FROM pemilik";
            Statement stat = conn.createStatement();
            Statement stat2 = conn.createStatement();
            Statement stat3 = conn.createStatement();
            Statement stat4 = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            ResultSet hasilMerk = stat2.executeQuery(sql2);
            ResultSet hasilTipe = stat3.executeQuery(sql3);
            ResultSet hasilPemilik = stat4.executeQuery(sql4);
            while (hasil.next()) {
                tabmode.addRow(new Object[]{
                    hasil.getString(1),
                    hasil.getString(2),
                    hasil.getString(3),
                    hasil.getString(4),
                    hasil.getString(5),
                    hasil.getString(6),
                    hasil.getString(7),
                    hasil.getString(8)
                });
            }
            merk.removeAllItems();
            while (hasilMerk.next()) {
                merk.addItem(hasilMerk.getString(2));
            }
            merk.setSelectedItem(null);
            tipe.removeAllItems();
            while (hasilTipe.next()) {
                tipe.addItem(hasilTipe.getString(2));
            }
            tipe.setSelectedItem(null);
            pemilik.removeAllItems();
            while (hasilPemilik.next()) {
                pemilik.addItem(hasilPemilik.getString(2));
            }
            pemilik.setSelectedItem(null);
            tblplgn.setModel(tabmode);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "data gagal dipanggil" + e);
        }
    }

    public void componentDidUpdate(String role, String usern) {
        jMenu9.setText("        Hi, " + usern);
        changeString(role, usern);
    }

    private String changeString(String s, String u) {
        this.userName = u;
        return this.roleUser = s;
    }

    private void cetak() {
        try {
            String path = "./src/report/kendaraan.jasper"; 
            HashMap parameter = new HashMap();
            JasperPrint print = JasperFillManager.fillReport(path, parameter, conn);
            JasperViewer.viewReport(print, false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "DokumenTidak Ada " + ex);

        }
    }
}
